#	$NetBSD: Makefile,v 1.2 2002/12/08 20:19:58 thorpej Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}bsdec2-image-upload
HOST_SRCDIR=	external/bsd/bsdec2-image-upload/bin

.include "${.CURDIR}/../Makefile.host"
